### ISSUE TITLE
Macos作服务端，Linux做客户端，二者无法建立连接

### ISSUE THREAD

**Issue by jylsec** [esrrhs/spp#15]
Macos信息如下
<img width="233" alt="image" src="https://user-images.githubusercontent.com/43801137/167065933-4545fcd4-16ae-4e92-986c-9a305cf18ba5.png">
Linux是ubuntu虚拟机
二者可以ping通，但是无法连接

使用命令如下：
```
./spp_linux -type server -proto ricmp -listen 0.0.0.0
./spp -name "test" -type reverse_socks5_client -server 192.168.79.1 -fromaddr :8080 -proxyproto tcp -proto ricmp
```

**Comment by esrrhs** [comment]
会不会和虚拟机有关系？

**Comment by jylsec** [comment]
> 会不会和虚拟机有关系？

Kali/ubuntu作服务器,ubuntu作客户端✅
macOS作服务器，ubuntu/Kali作客户端❌
Kali/ubuntu作服务器，macOS作客户端✅
