### ISSUE TITLE
域名使用cdn加速后无法正常使用

### ISSUE THREAD

**Issue by Lynx-777** [esrrhs/spp#18]
你好，非常喜欢你的这个代理工具，但我现在遇到个问题，域名直接解析IP的情况可以正常连接SPP服务端，如果域名使用了CDN的情况这样就无法正常连接上SPP的服务端了，这个怎么回事呢,能完善一下吗。
例：
./spp -name "test" -type reverse_socks5_client -server www.test.com:8888 -fromaddr :1080 -proxyproto tcp

**Comment by esrrhs** [comment]
是指的www.test.com变成了用CDN加速的比如www.testcdn.com吗？这种情况就要看他怎么加速的了，加速本质应该也是一种代理，得看他内部走的什么协议，可以确定肯定不是spp的自有通信协议，那自然连不上了

**Comment by Lynx-777** [comment]
在没使用CDN加速的时候，www.test.com域名直接添加A记录解析到SPP服务端的IP，这个时候使用./spp -name "test" -type reverse_socks5_client -server www.test.com:8888 -fromaddr :1080 -proxyproto tcp是可以正常使用的。

当www.test.com变成了用CDN加速，我使用cloudflare的CDN对www.test.com加速之后，在使用以上方法连接SPP服务端就无法连接了，虽然SPP服务端能收到连接请求，但不能正常连接上。

**Comment by esrrhs** [comment]
他加速的应该是http、https协议

**Comment by 2605759123** [comment]
cloudflare只加速http、https协议的特定端口
https://zhuanlan.zhihu.com/p/466538907
