### ISSUE TITLE
建议完善一下帮助

### ISSUE THREAD

**Issue by chmis8000** [esrrhs/spp#2]
1.举例： -fromaddr :8080 -toaddr :8080  这个最好端口不一样，方便描述时能够区分哪台机子，另外 -toaddr 测试是支持映射内网机子，建议举例。
2.-compress 默认是 128，还可以是0不压缩，那还有其他值吗？  压缩用的什么算法？
3.-encrypt 与 -encrypt 有什么区别，性能损失估计什么情况？
4.-maxclient 与 -maxconn 一个默认8 一个默认128 ，不清楚有什么区别
5.-name 这个默认是 "client"，是不能重名吗？ 还是为了以后有了web管理端后，可以人为区分这是什么业务？
6.-ping 、-profile 不清楚什么意义
7.pingtunnel 有 -timeout 参数，这个为啥没有参数了，目前测试好像是超时 20 秒？

**Comment by esrrhs** [comment]
嗯，可以，回头弄详细点

**Comment by chmis8000** [comment]
改一下，写的错误： 正确：
3.-encrypt 与 -key 有什么区别

**Comment by Pretexts** [comment]
-nolog 不会用，怎么才能不生成日志呢

**Comment by esrrhs** [comment]
> 
> 
> -nolog 不会用，怎么才能不生成日志呢

 -nolog 1
