### ISSUE TITLE
ICMP tunnel?

### ISSUE THREAD

**Issue by asterriya** [esrrhs/spp#20]
What happened with your other git https://github.com/esrrhs/pingtunnel, because I need that tool. Can you return it back? Spp not compatible with my network environment. Please. It's very important for me.

**Comment by esrrhs** [comment]
use the [delete] branch

**Comment by asterriya** [comment]
Done, but still hope that you will fix script and make it work right. Cheers.

**Comment by asterriya** [comment]
So pingtunnel wouldn't development progress anymore?

**Comment by esrrhs** [comment]
yes, for some security reasons
