### ISSUE TITLE
我用这个程序的“tcp正向socks5代理”功能翻墙成功，不过连接是加密的吗？

### ISSUE THREAD

**Issue by luckypoem** [esrrhs/spp#4]
服务器端：spp -type server -proto tcp -listen :8888

客户端：spp -type socks5_client -server vps-public-ip:8888 -fromaddr 127.0.0.1:8080 -proxyproto tcp

然后设置浏览器的socks5代理地址为127.0.0.1 ，端口为8080，浏览器确实可以翻墙，不过连接是加密的吗？

我看2边的参数，感觉好像没加密？

**Comment by esrrhs** [comment]
-h看看
"encrypt key, empty means off"

**Comment by luckypoem** [comment]
hi.

感觉你那个pingtunnel有点奇怪：
pingtunnel -type server 怎么不监听端口的吗？还是它默认监听某个端口？（默认监听哪个端口？）

客户机器上的命令：
sudo ./pingtunnel -type client -l 127.0.0.1:2299 -s vps-public-ip -sock5 1
也没有显示监听服务器的哪个端口

另外，pingtunnel -h看不到有‘-encrypt’参数，那么pingtunnel应该没有加密吧？

**Comment by esrrhs** [comment]
> 
> 
> hi.
> 
> 感觉你那个pingtunnel有点奇怪：
> pingtunnel -type server 怎么不监听端口的吗？还是它默认监听某个端口？（默认监听哪个端口？）
> 
> 客户机器上的命令：
> sudo ./pingtunnel -type client -l 127.0.0.1:2299 -s vps-public-ip -sock5 1
> 也没有显示连接服务器的哪个端口
> 
> 另外，pingtunnel -h看不到有‘-encrypt’参数，那么pingtunnel应该没有加密吧？

你了解一下icmp协议，端口的概念是tcp udp

**Comment by luckypoem** [comment]
"端口的概念是tcp udp"- 哦，明白了。不过pingtunnel -h看不到有‘-encrypt’参数，那么pingtunnel应该没有加密吧？
谢谢回复
