### ISSUE TITLE
可以实现以下场景吗？

### ISSUE THREAD

**Issue by Z-fly** [esrrhs/spp#8]
程序只运行在服务器上，开启代理，设置用户名密码认证

我目前是用 https://github.com/qwj/python-proxy 实现

**Comment by esrrhs** [comment]
> 
> 
> 程序只运行在服务器上，开启代理，设置用户名密码认证
> 
> 我目前是用 https://github.com/qwj/python-proxy 实现

只跑在服务器，那么你就必须用常规协议去连接了，那就失去用这个的意义了

**Comment by Z-fly** [comment]
> > 程序只运行在服务器上，开启代理，设置用户名密码认证
> > 我目前是用 https://github.com/qwj/python-proxy 实现
> 
> 只跑在服务器，那么你就必须用常规协议去连接了，那就失去用这个的意义了

这个是把数据加密压缩 需要有客户端做特点接收是吗

**Comment by esrrhs** [comment]
> 
> 
> > > 程序只运行在服务器上，开启代理，设置用户名密码认证
> > > 我目前是用 https://github.com/qwj/python-proxy 实现
> > 
> > 
> > 只跑在服务器，那么你就必须用常规协议去连接了，那就失去用这个的意义了
> 
> 这个是把数据加密压缩 需要有客户端做特点接收是吗

用spp做中间的信道传输才有意义，比如加密压缩等等，或者走udp icmp协议
